//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS4396Solution
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicYr
    {
        public string AcademicYrCd { get; set; }
        public string AcademicYrDesc { get; set; }
        public string ActiveInd { get; set; }
        public System.DateTime CreaetDt { get; set; }
        public string CreateUserNm { get; set; }
    }
}
