//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS4396Solution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public string AreaCd { get; set; }
        public string AreaNm { get; set; }
        public string ActiveInd { get; set; }
        public Nullable<System.DateTime> CreateDt { get; set; }
        public Nullable<System.DateTime> LastModDt { get; set; }
        public string LastModUser { get; set; }
    }
}
